from enum import Enum

from src.constants import CC_MTG_FILE_STUB, CC_MTG_FILE_TEMPLATE, DOWNLOADED_CC_MTG_KEY, EXTRACTED_CC_MTG_KEY, \
    COMPRESSED_CC_MTG_KEY, SCRAPED_CC_MTG_KEY, AUDIO_TRANSCRIBED_CC_MTG_KEY, TRANSCRIPT_UPLOADED_CC_MTG_KEY, \
    VIDEO_UPLOADED_CC_MTG_KEY
from src.settings import DOWNLOADED_DIR, COMPRESSED_DIR, EXTRACTED_AUDIO_DIR, TRANSCRIBED_DIR


class SourceType(Enum):
    CITY_COUNCIL_MEETING = 1
    BUDGET_AND_AUDIT_MEETING = 2


type_stubs = {
    SourceType.CITY_COUNCIL_MEETING: CC_MTG_FILE_STUB
}


class JobType(Enum):
    SCRAPE = 1
    DOWNLOAD = 2
    COMPRESS = 3
    EXTRACT_AUDIO = 4
    TRANSCRIBE_AUDIO = 5
    UPLOAD_TRANSCRIPT = 6
    UPLOAD_VIDEO = 7


job_paths = {
    JobType.DOWNLOAD: DOWNLOADED_DIR,
    JobType.COMPRESS: COMPRESSED_DIR,
    JobType.EXTRACT_AUDIO: EXTRACTED_AUDIO_DIR,
    JobType.TRANSCRIBE_AUDIO: TRANSCRIBED_DIR,
}


source_file_templates = {
    SourceType.CITY_COUNCIL_MEETING: CC_MTG_FILE_TEMPLATE,
}

job_file_formats = {
    JobType.DOWNLOAD: '.mp4',
    JobType.COMPRESS: '.mp4',
    JobType.EXTRACT_AUDIO: '.m4a',
    JobType.TRANSCRIBE_AUDIO: '.txt',
}

job_redis_keys = {
    JobType.SCRAPE: SCRAPED_CC_MTG_KEY,
    JobType.DOWNLOAD: DOWNLOADED_CC_MTG_KEY,
    JobType.COMPRESS: COMPRESSED_CC_MTG_KEY,
    JobType.EXTRACT_AUDIO: EXTRACTED_CC_MTG_KEY,
    JobType.TRANSCRIBE_AUDIO: AUDIO_TRANSCRIBED_CC_MTG_KEY,
    JobType.UPLOAD_TRANSCRIPT: TRANSCRIPT_UPLOADED_CC_MTG_KEY,
    JobType.UPLOAD_VIDEO: VIDEO_UPLOADED_CC_MTG_KEY,
}